version: '3.8'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
     
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=12345!#@$
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    networks:
      - backend
    restart: on-failure

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - backend

networks:
  backend:

volumes:
  sqlvolume: